apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beaveragent
  namespace: ik8s-system
spec:
  selector:
    matchLabels:
      name: ik8s-beaveragent
  template:
    metadata:
      labels:
        name: ik8s-beaveragent
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/storage
        effect: NoSchedule
      - key: node-role.kubernetes.io/storage-node
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: vswitch
        # imagePullPolicy: Always
        image: dr.ik8s.ir/beaveragent:0.1.0-alpha1
        securityContext:
          privileged: true
          capabilities:
            add: 
            - NET_ADMIN
            - SYS_MODULE
            - SYS_NICE
 
        volumeMounts:
        - mountPath: /host/var/run/openvswitch
          name: nodeovsrun
        - mountPath: /host/var/lib/openvswitch
          name: nodeovslib
        - mountPath: /lib/modules
          name: kernel-modules
      volumes:
      - name: nodeovsrun
        hostPath:
          path: /var/run/openvswitch
      - name: nodeovslib
        hostPath:
          path: /var/lib/openvswitch
      - name: kernel-modules
        hostPath:
          path: /lib/modules